/**
 * The three digests. Every number comes from lib/metrics via
 * lib/metrics/service — the same call path the Command Center uses. The
 * weekly/monthly scorecard is lib/scorecard/assemble's model rendered as
 * HTML — the /scorecard page renders the identical model.
 *
 * Scorecard rules: one timeframe per digest; `empty` tells the sender to
 * skip rather than mail a page of zeros.
 */

import { getScorecard, getTodoBuckets } from '../metrics/service';
import { TODO_LABELS, REBOOK_LABELS, formatCents, type TodoKind, type RebookKind } from '../metrics';
import { assembleScorecard, type ScorecardView, type ScorecardStat } from '../scorecard/assemble';
import { formatLongDate } from '../dates';
import { shell, sectionTitle, note, statRow, table, peopleList, textHeader, textTable, escapeHtml } from './templates';
import { getNarrative } from '../anthropic/narrative';

export type DigestKind = 'daily_todo' | 'weekly' | 'monthly';

export interface Digest {
  kind: DigestKind;
  periodStart: string;
  periodEnd: string;
  subject: string;
  html: string;
  text: string;
  empty: boolean;
}

export const DIGEST_LABELS: Record<DigestKind, string> = {
  daily_todo: 'Daily to-do',
  weekly: 'Weekly scorecard',
  monthly: 'Monthly scorecard',
};

// ---------------------------------------------------------------------------
// Daily to-do
// ---------------------------------------------------------------------------

const TODO_ORDER: TodoKind[] = ['applied_no_booking', 'consult_noshow', 'roadmap_noshow'];

export async function buildDailyTodo(today?: string): Promise<Digest> {
  const { today: day, buckets } = await getTodoBuckets(today);
  const title = formatLongDate(day);

  const section = (label: string, bucket: typeof buckets.day1) => {
    const count = TODO_ORDER.reduce((s, k) => s + bucket[k].length, 0);
    return (
      sectionTitle(label, `${count} ${count === 1 ? 'person' : 'people'}`) +
      TODO_ORDER.map(
        (k) =>
          `<div style="font-size:12.5px;font-weight:600;color:#55585e;margin-top:8px;">${TODO_LABELS[k]} (${bucket[k].length})</div>` +
          peopleList(bucket[k]),
      ).join('')
    );
  };

  const REBOOK_ORDER: RebookKind[] = ['consult_rescheduled', 'roadmap_rescheduled'];
  const rebookCount = REBOOK_ORDER.reduce((s, k) => s + buckets.awaitingRebook[k].length, 0);
  const rebookSection =
    sectionTitle('Awaiting rebook', `${rebookCount} ${rebookCount === 1 ? 'person' : 'people'} · listed every day until they rebook`) +
    REBOOK_ORDER.map(
      (k) =>
        `<div style="font-size:12.5px;font-weight:600;color:#55585e;margin-top:8px;">${REBOOK_LABELS[k]} (${buckets.awaitingRebook[k].length})</div>` +
        peopleList(buckets.awaitingRebook[k].map((p) => ({ ...p, on: `${p.on} · waiting ${p.daysWaiting} day${p.daysWaiting === 1 ? '' : 's'}` }))),
    ).join('');

  const bodyHtml =
    (buckets.total === 0 ? note('Nothing needs a call today.') : '') +
    section('Day-1 follow-ups', buckets.day1) +
    section('Day-3 follow-ups', buckets.day3) +
    rebookSection;

  const textLines = textHeader('Daily to-do', title);
  for (const [label, bucket] of [
    ['DAY-1 FOLLOW-UPS', buckets.day1],
    ['DAY-3 FOLLOW-UPS', buckets.day3],
  ] as const) {
    textLines.push(label, '-'.repeat(40));
    for (const k of TODO_ORDER) {
      textLines.push(`${TODO_LABELS[k]} (${bucket[k].length})`);
      for (const p of bucket[k]) textLines.push(`  - ${p.name} — ${p.email ?? 'no email'} — ${p.source ?? 'source unknown'} — ${p.on}`);
    }
    textLines.push('');
  }
  textLines.push('AWAITING REBOOK (every day until they rebook)', '-'.repeat(40));
  for (const k of REBOOK_ORDER) {
    textLines.push(`${REBOOK_LABELS[k]} (${buckets.awaitingRebook[k].length})`);
    for (const p of buckets.awaitingRebook[k]) {
      textLines.push(`  - ${p.name} — ${p.email ?? 'no email'} — ${p.source ?? 'source unknown'} — since ${p.on} (${p.daysWaiting} day${p.daysWaiting === 1 ? '' : 's'})`);
    }
  }
  textLines.push('');

  return {
    kind: 'daily_todo',
    periodStart: day,
    periodEnd: day,
    subject: `FitFlow to-do — ${title} (${buckets.total} to call)`,
    html: shell({
      kicker: 'Daily to-do',
      title,
      subtitle: 'Day-1 and Day-3 follow-ups · awaiting rebook',
      bodyHtml,
      footerNote: 'Day-1 = happened yesterday. Day-3 = three days ago and still not moved. Awaiting rebook = in a rescheduled stage; repeats daily until they leave it. Read-only mirror of GoHighLevel.',
    }),
    text: textLines.join('\n'),
    empty: buckets.total === 0,
  };
}

// ---------------------------------------------------------------------------
// Weekly / monthly scorecard (same template, different grain)
// ---------------------------------------------------------------------------

async function buildScorecard(kind: 'weekly' | 'monthly', today?: string): Promise<Digest> {
  // Narrative is generated by the nightly job (lib/anthropic/narrative.ts);
  // here we only read what exists. No key → no section.
  const range = kind === 'weekly' ? 'last_week' : 'last_month';
  // NOTE: getScorecard resolves 'today' from the business timezone itself;
  // the `today` override only applies to the daily to-do (tests).
  void today;
  const result = await getScorecard({ range, compare: 'previous_period' });
  const r = result.range;
  const narrative = await getNarrative(kind, r.start, r.end);
  // The /scorecard page renders this same model — the email is that page in HTML.
  const view = assembleScorecard(result, narrative);
  return renderScorecardDigest(kind, view, r);
}

/** Render an assembled scorecard as the email (HTML + plain text). Pure. */
export function renderScorecardDigest(kind: 'weekly' | 'monthly', view: ScorecardView, r: { start: string; end: string }): Digest {
  const card = (st: ScorecardStat) => ({ label: st.label, value: st.value, sub: st.sub, tone: st.tone });
  const campaignLine = view.campaigns.top
    ? `Best cost per client: ${view.campaigns.top.campaignName} (${formatCents(view.campaigns.top.costPerEnrollmentCents)}/client, ${view.campaigns.top.enrolled} enrolled from ${formatCents(view.campaigns.top.spendCents)}).` +
      (view.campaigns.worst ? ` Worst: ${view.campaigns.worst.campaignName} (${formatCents(view.campaigns.worst.costPerEnrollmentCents)}/client, ${view.campaigns.worst.enrolled} enrolled from ${formatCents(view.campaigns.worst.spendCents)}).` : '') +
      (view.campaigns.note ? ` ${view.campaigns.note}` : '')
    : view.campaigns.note;

  const narrativeHtml = view.narrative
    ? sectionTitle(view.narrativeTitle) + `<p style="font-size:14px;line-height:1.55;color:#0c0d0e;margin:0 0 6px;">${escapeHtml(view.narrative)}</p>`
    : '';

  const bodyHtml =
    narrativeHtml +
    sectionTitle('Money') +
    statRow(view.sections.money.map(card)) +
    sectionTitle('Pipeline') +
    statRow(view.sections.pipeline.map(card)) +
    sectionTitle('Ads') +
    statRow(view.sections.ads.map(card)) +
    `<div style="font-size:12.5px;color:#55585e;margin:8px 0 0;">${escapeHtml(campaignLine)}</div>` +
    view.notes.map((n) => note(n.text, n.tone)).join('') +
    sectionTitle('Funnel', view.period.label) +
    table(['Stage', 'Count', 'Of applied', 'From previous', 'Cost per'], view.funnelRows, ['left', 'right', 'right', 'right', 'right']) +
    sectionTitle('Customer acquisition cost') +
    `<div style="font-size:13px;color:#55585e;">${escapeHtml(view.cacLine)}</div>` +
    sectionTitle('Show rates') +
    table(['Type', 'Showed', 'No-show', 'Cancelled', 'Show rate'], view.showRows, ['left', 'right', 'right', 'right', 'right']) +
    sectionTitle('Top sources') +
    table(['Source', 'Applied', 'Consults', 'Enrolled', 'Applied → client'], view.sourceRows, ['left', 'right', 'right', 'right', 'right']);

  const statLines = (stats: ScorecardStat[]) => stats.map((c) => `${c.label.padEnd(22)} ${c.value.padEnd(10)} ${c.sub}`);
  const text = [
    ...textHeader(DIGEST_LABELS[kind], view.title, view.subtitle),
    ...(view.narrative ? [view.narrative, ''] : []),
    'MONEY',
    ...statLines(view.sections.money),
    '',
    'PIPELINE',
    ...statLines(view.sections.pipeline),
    '',
    'ADS',
    ...statLines(view.sections.ads),
    campaignLine,
    '',
    ...view.notes.map((n) => n.text),
    '',
    'FUNNEL',
    ...textTable(['Stage', 'Count', 'Of applied', 'From prev', 'Cost per'], view.funnelRows),
    '',
    'CUSTOMER ACQUISITION COST',
    view.cacLine,
    '',
    'SHOW RATES',
    ...textTable(['Type', 'Showed', 'No-show', 'Cancelled', 'Rate'], view.showRows),
    '',
    'TOP SOURCES',
    ...textTable(['Source', 'Applied', 'Consults', 'Enrolled', 'Applied→client'], view.sourceRows),
  ].join('\n');

  return {
    kind,
    periodStart: r.start,
    periodEnd: r.end,
    subject: view.subject,
    html: shell({ kicker: DIGEST_LABELS[kind], title: view.title, subtitle: view.subtitle, bodyHtml }),
    text,
    empty: view.empty,
  };
}

export function buildWeeklyScorecard(today?: string): Promise<Digest> {
  return buildScorecard('weekly', today);
}

export function buildMonthlyScorecard(today?: string): Promise<Digest> {
  return buildScorecard('monthly', today);
}

export function buildDigest(kind: DigestKind, today?: string): Promise<Digest> {
  if (kind === 'daily_todo') return buildDailyTodo(today);
  if (kind === 'weekly') return buildWeeklyScorecard(today);
  return buildMonthlyScorecard(today);
}

export function isDigestKind(value: unknown): value is DigestKind {
  return value === 'daily_todo' || value === 'weekly' || value === 'monthly';
}
