CREATE TABLE `lead_events` (
	`id` text PRIMARY KEY NOT NULL,
	`lead_id` text NOT NULL,
	`action` text NOT NULL,
	`prior_stage` text,
	`new_stage` text,
	`appointment_status` text,
	`actor` text DEFAULT 'system' NOT NULL,
	`notes` text,
	`metadata` text,
	`sync_status` text DEFAULT 'local',
	`sync_error` text,
	`ghl_event_id` text,
	`created_at` text NOT NULL,
	FOREIGN KEY (`lead_id`) REFERENCES `leads`(`id`) ON UPDATE no action ON DELETE cascade
);
--> statement-breakpoint
CREATE TABLE `leads` (
	`id` text PRIMARY KEY NOT NULL,
	`first_name` text NOT NULL,
	`last_name` text NOT NULL,
	`email` text NOT NULL,
	`phone` text,
	`pipeline_id` text DEFAULT '[new] Application Pipeline' NOT NULL,
	`pipeline_name` text DEFAULT '[new] Application Pipeline' NOT NULL,
	`stage` text NOT NULL,
	`status` text DEFAULT 'active',
	`source` text,
	`original_source` text,
	`utm_source` text,
	`utm_campaign` text,
	`utm_medium` text,
	`utm_content` text,
	`entry_funnel` text,
	`ghl_source` text,
	`appointment_id` text,
	`appointment_time` text,
	`appointment_status` text DEFAULT 'scheduled',
	`estimated_value` real DEFAULT 0,
	`owner` text,
	`tags` text,
	`notes` text,
	`consult_outcome` text,
	`roadmap_outcome` text,
	`created_at` text NOT NULL,
	`updated_at` text NOT NULL,
	`date_applied` text,
	`last_action_at` text,
	`days_in_stage` integer DEFAULT 0
);
