import { sql } from 'drizzle-orm';
import { sqliteTable, text, integer, real, primaryKey } from 'drizzle-orm/sqlite-core';

// Leads table: represents prospects/opportunities
export const leads = sqliteTable('leads', {
  id: text('id').primaryKey().$defaultFn(() => crypto.randomUUID()),

  // Contact info
  firstName: text('first_name').notNull(),
  lastName: text('last_name').notNull(),
  email: text('email').notNull(),
  phone: text('phone'),

  // Pipeline tracking
  pipelineId: text('pipeline_id').notNull().default('[new] Application Pipeline'),
  pipelineName: text('pipeline_name').notNull().default('[new] Application Pipeline'),
  stage: text('stage').notNull(), // Applied, Consult Booked, Consult No Show, Pre-Roadmap Booked, Roadmap No Show, Roadmap Completed: Objection, Enrolled
  status: text('status').default('active'), // active, archived

  // Attribution & source
  source: text('source'), // Facebook, Instagram, Google, Referral, Website, etc.
  originalSource: text('original_source'), // Never overwritten
  utmSource: text('utm_source'),
  utmCampaign: text('utm_campaign'),
  utmMedium: text('utm_medium'),
  utmContent: text('utm_content'),
  entryFunnel: text('entry_funnel'), // Application 7.10, etc.
  ghlSource: text('ghl_source'), // GHL's native source

  // Appointment tracking
  appointmentId: text('appointment_id'),
  appointmentTime: text('appointment_time'), // ISO 8601 timestamp
  appointmentStatus: text('appointment_status').default('scheduled'), // scheduled, attended, no_show, cancelled, rescheduled

  // Business data
  estimatedValue: real('estimated_value').default(0), // in cents or dollars
  owner: text('owner'), // Miranda, Jake, etc.
  tags: text('tags'), // JSON array of tag names
  notes: text('notes'),

  // Outcomes (for reporting)
  consultOutcome: text('consult_outcome'), // Attended, No-Show, Cancelled
  roadmapOutcome: text('roadmap_outcome'), // Attended, No-Show, Objection, Enrolled

  // Timestamps
  createdAt: text('created_at').notNull().$defaultFn(() => new Date().toISOString()),
  updatedAt: text('updated_at').notNull().$defaultFn(() => new Date().toISOString()),
  dateApplied: text('date_applied'),

  // FitFlow-specific tracking
  lastActionAt: text('last_action_at'),
  daysInStage: integer('days_in_stage').default(0),

  // Provenance. 'demo' rows are fabricated sample data generated by the seed
  // script; 'ghl' rows were imported from a real GoHighLevel account; 'manual'
  // was entered by hand. Surfaced in the UI so invented numbers can never be
  // mistaken for real performance.
  origin: text('origin').notNull().default('demo'), // demo | ghl | manual

  // GoHighLevel linkage (null until imported)
  ghlContactId: text('ghl_contact_id'),
  ghlOpportunityId: text('ghl_opportunity_id'),
  ghlPipelineId: text('ghl_pipeline_id'),
  ghlStageId: text('ghl_stage_id'),
  lastImportedAt: text('last_imported_at'),
});

// Lead events: immutable audit trail
export const leadEvents = sqliteTable('lead_events', {
  id: text('id').primaryKey().$defaultFn(() => crypto.randomUUID()),

  // Link to lead
  leadId: text('lead_id').notNull().references(() => leads.id, { onDelete: 'cascade' }),

  // Action details
  action: text('action').notNull(), // MarkAttended, MarkNoShow, CreateFollowUp, Reschedule, Enroll
  priorStage: text('prior_stage'),
  newStage: text('new_stage'),
  appointmentStatus: text('appointment_status'), // What we marked it as

  // Actor
  actor: text('actor').notNull().default('system'), // Who performed the action

  // Notes & metadata
  notes: text('notes'),
  metadata: text('metadata'), // JSON field for extra data

  // Sync status (for Phase 2: GHL integration)
  syncStatus: text('sync_status').default('local'), // local, syncing, synced, failed
  syncError: text('sync_error'),
  ghlEventId: text('ghl_event_id'),

  // Timestamp
  createdAt: text('created_at').notNull().$defaultFn(() => new Date().toISOString()),
});

// Appointments: the unit of work for the Today View.
// One row per scheduled session. `ghlEventId` links back to a GHL calendar event.
export const appointments = sqliteTable('appointments', {
  id: text('id').primaryKey().$defaultFn(() => crypto.randomUUID()),

  // Link to lead
  leadId: text('lead_id').notNull().references(() => leads.id, { onDelete: 'cascade' }),

  // GHL linkage (null until synced / imported)
  ghlEventId: text('ghl_event_id'),
  ghlCalendarId: text('ghl_calendar_id'),
  ghlContactId: text('ghl_contact_id'),
  ghlOpportunityId: text('ghl_opportunity_id'),

  // Appointment identity.
  // GHL has no appointmentType field - type is a property of the calendar the
  // appointment lives on, so we denormalise the calendar's name into `type`.
  type: text('type').notNull().default('Consult'), // Consult, Roadmap, Follow-Up, Check-In
  title: text('title'),

  // Scheduling (ISO 8601 with offset, matching GHL's format)
  startTime: text('start_time').notNull(),
  endTime: text('end_time'),
  timezone: text('timezone').notNull().default('America/New_York'),

  // Who's running it
  assignedTo: text('assigned_to'),
  ghlAssignedUserId: text('ghl_assigned_user_id'),

  // Attendance outcome - the whole point of the Today View.
  // null = not yet marked. Set by staff clicking Booked/No Show/Not Continuing.
  outcome: text('outcome'), // booked, no_show, not_continuing
  outcomeNotes: text('outcome_notes'),
  outcomeMarkedAt: text('outcome_marked_at'),
  outcomeMarkedBy: text('outcome_marked_by'),

  // Mirror of GHL's appointmentStatus enum: new|confirmed|showed|noshow|cancelled|invalid
  ghlAppointmentStatus: text('ghl_appointment_status').default('confirmed'),

  // Sync lifecycle
  syncStatus: text('sync_status').notNull().default('pending'), // pending, queued, synced, failed, skipped
  syncedAt: text('synced_at'),

  // See leads.origin.
  origin: text('origin').notNull().default('demo'), // demo | ghl | manual
  lastImportedAt: text('last_imported_at'),

  createdAt: text('created_at').notNull().$defaultFn(() => new Date().toISOString()),
  updatedAt: text('updated_at').notNull().$defaultFn(() => new Date().toISOString()),
});

// Outbox pattern: every GHL write is enqueued here first, then drained by the
// midnight job. GHL has no transaction semantics across endpoints, so each
// individual API call gets its own retryable row.
export const ghlSyncQueue = sqliteTable('ghl_sync_queue', {
  id: text('id').primaryKey().$defaultFn(() => crypto.randomUUID()),

  appointmentId: text('appointment_id').references(() => appointments.id, { onDelete: 'cascade' }),
  leadId: text('lead_id').references(() => leads.id, { onDelete: 'cascade' }),

  // What to do
  operation: text('operation').notNull(), // update_appointment_status, create_appointment_note, update_opportunity_stage, update_opportunity_status, add_contact_tag
  endpoint: text('endpoint').notNull(),
  method: text('method').notNull().default('PUT'),
  payload: text('payload').notNull(), // JSON body

  // Ordering - step 1 (appointment status) is authoritative and must land first
  sequence: integer('sequence').notNull().default(0),

  // Lifecycle
  status: text('status').notNull().default('pending'), // pending, in_flight, succeeded, failed, dry_run
  attempts: integer('attempts').notNull().default(0),
  lastError: text('last_error'),
  responseBody: text('response_body'),

  scheduledFor: text('scheduled_for'), // ISO timestamp - midnight batch
  processedAt: text('processed_at'),

  createdAt: text('created_at').notNull().$defaultFn(() => new Date().toISOString()),
});

// Simple key/value store for app configuration that persists across restarts.
// Holds the remembered day-summary recipient email, GHL ids, timezone, etc.
export const appSettings = sqliteTable('app_settings', {
  key: text('key').primaryKey(),
  value: text('value'),
  updatedAt: text('updated_at').notNull().$defaultFn(() => new Date().toISOString()),
});

// Export types for TypeScript
export type Lead = typeof leads.$inferSelect;
export type NewLead = typeof leads.$inferInsert;
export type LeadEvent = typeof leadEvents.$inferSelect;
export type NewLeadEvent = typeof leadEvents.$inferInsert;
export type Appointment = typeof appointments.$inferSelect;
export type NewAppointment = typeof appointments.$inferInsert;
export type GhlSyncQueueItem = typeof ghlSyncQueue.$inferSelect;
export type NewGhlSyncQueueItem = typeof ghlSyncQueue.$inferInsert;
export type AppSetting = typeof appSettings.$inferSelect;
